version: '3'

services:
  nodegoat:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000

  juice-shop:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:3000

  webgoat:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080

  dvwa:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80

  nosqlmap:
    build:
      context: .
      dockerfile: Dockerfile

  sql-injection:
    build:
      context: .
      dockerfile: Dockerfile

  bwapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 81:80

  dvws:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 82:80

  webgoat-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:8080

  juice-shop-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4001:3000

  insecure-iot:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000

  scada:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9000:9000

